on:
  push:
    branches:
      - master
    








jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: "test"
        run: pwd
      - uses: actions/checkout@v3  
      - name: "printing"
        run: ls
      