on:
  push:
    branches:
      - master:
    








job:
  build:
    run-on: ubuntu-latest


    steps:
      - name: "test"
        run: pwd
      - name: "test2"
        run: echo mohamed
      